In [30]:
import numpy as np
import pandas as pd

# 예제 5

In [33]:
# list = []
# for i in ag:
#     list.append(ag[i].sin())
#     list.append(ag[i].cos())
#     list.append(ag[i].tan())

In [58]:
# 삼각함수를 올바르게 사용하기 위해서는 각도를 라디안으로 변환
arr = np.array([0, 30, 60, 90])
lst = []
lst.append(np.sin(arr * np.pi / 180))
lst.append(np.cos(arr * np.pi / 180))
lst.append(np.tan(arr * np.pi / 180))
    
for value_lst in lst:
    for value in value_lst:
        if value > 999999999:
            print('INF')
            continue;
        print(value)
    print()

0.0
0.49999999999999994
0.8660254037844386
1.0

1.0
0.8660254037844387
0.5000000000000001
6.123233995736766e-17

0.0
0.5773502691896257
1.7320508075688767
INF



In [36]:
# if result_list[i].isfinite:
#     replace(result_list[i], 'INF')

In [37]:
# for i in range(len(result_list)):
#     if np.isfinite(result_list[i]):
#         result_list[i] = 'INF'

# 예제 6

In [75]:
# arr = np.array([0,1])
# tile = np.tile(arr, reps = 3)
# print(tile)

# rep = np.repeat(tile, repeats = 5)
# print(rep)

[0 1 0 1 0 1]
[0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1 0 0 0 0 0 1 1 1 1 1]


In [81]:
arr = np.zeros((7, 7), dtype =int)
print(arr)

[[0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]]


In [82]:
arr[::2, 1::2] = 1
arr[1::2, ::2] = 1
print(arr)

[[0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]
 [1 0 1 0 1 0 1]
 [0 1 0 1 0 1 0]]


In [84]:
for row in range(7): # arr의 각 요소를 출력
    for col in range(7):
        print(arr[row, col], end=" ") # 한 줄에 여러 요소를 출력한 후 줄 바꿈
    print() #  7x7 배열의 모든 요소가 공백으로 구분되어 한 줄에 출력
    
#  2차원 배열의 경우, 각 행과 열을 구분하고 요소들을 정렬된 형태로 출력하기 위해 이러한 방식을 사용
# 각 행에 대한 반복문이 외부에 위치하고, 각 열에 대한 반복문이 내부에 위치

0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
1 0 1 0 1 0 1 
0 1 0 1 0 1 0 
